variables:
  majorVersion: 0
  minorVersion: 0
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]
  version: $[format('{0}.{1}.{2}', variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]

name: $(version)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

stages:
  - stage: buildAndRelease
    displayName: Build & Release
    jobs:
      - job: buildAndRelease
        displayName: Build & Release
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet restore'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'config'
              nugetConfigPath: '$(System.DefaultWorkingDirectory)/nuget.config'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              command: 'build'
              projects: '**/*.csproj'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'byBuildNumber'

          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'NuGet.org'