variables:
  majorVersion: 0
  minorVersion: 0
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]
  version: $[format('{0}.{1}.{2}', variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]

name: $(version)

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-18.04"
steps:
  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: "**/*.csproj"
      versioningScheme: byBuildNumber

  - task: NuGetCommand@2
    inputs:
      command: push
      feedsToUse: config
      includeNugetOrg: true